### ISSUE TITLE
Bug - 'Apps' (cube icon) throwing an error (Java) or 'Apps isn't working'

### ISSUE THREAD

**Issue by Consulere** [GrapheneOS/Apps#280]
Bug

Severity - High
Urgency - Low/Medium (depends if others can reproduce it or what's the latest version of 'Apps')

Environment:
Google Pixel 6a

Steps:
GIVEN I have updated to the latest GrapheneOS version
AND I have opened either Owner profile on GrapheneOS
OR I have opened a Profile with Google Play ect... installed
WHEN I select the 'Apps' icon (cube shaped icon)
THEN I see an error
like: 'App isn't working'

Other
GIVEN I have opened either default profile on GrapheneOS
AND I select Settings
WHEN I select 'Apps'
THEN I see Installed version 14

On 7/02/2023 I had 'Apps' throw a java error but I didn't screenshot it sadly.
Workaround:
On 08/02/2023, I disabled the 'Apps' and now have enabled it and added it to the home screen via settings, it now shows no errors.

Just would like to know what's the latest version to avoid this being some security issue?

**Comment by Consulere** [comment]
Please add a bug label as I don't seem to have permissions to do so.

**Comment by Consulere** [comment]
@thestinger Thanks

**Comment by thestinger** [comment]
It's not really clear what you mean by 'either default profile' because by default there's only the Owner user.

You need to try to get a log of the crash. You can obtain that with the capture bug report feature in developer options or with `adb logcat`. Don't post the bug report zip here but rather email it to us since it can contain sensitive information if apps leak it to the logs. You may prefer fetching logs with `adb logcat -d > log.txt` where you can find the crash in the log and then only post the relevant portion here.

**Comment by Consulere** [comment]
It's not really clear what you mean by 'either default profile' because by default there's only the Owner user.

I mean Owner, corrected bug report

You need to try to get a log of the crash. You can obtain that with the capture bug report feature in developer options or with adb logcat. Don't post the bug report zip here but rather email it to us since it can contain sensitive information if apps leak it to the logs. You may prefer fetching logs with adb logcat -d > log.txt where you can find the crash in the log and then only post the relevant portion here.

Will do, probably be sent over later today/tomorrow, thank you

**Comment by r3g-5z** [comment]
Don't really understand the bug here. Please try updating Apps to latest and updating to latest GrapheneOS release. Going to assume we unintentionally fixed it. It might have just been an edge-case crash that we fixed.

**Comment by User1966** [comment]
This is still happening regularly, not sure why

I am in the process of sending my device back for warrenty/hot battery (issue above visible before this) so reflashing the OS might fix it, though restoring from the backup might not help with debugging

**Comment by User1966** [comment]
@girlbossceo 
This is still happening regularly, not sure why

I am in the process of sending my device back for warrenty/hot battery (issue above visible before this) so reflashing the OS might fix it, though restoring from the backup might not help with debugging

Do you want a new bug?

**Comment by thestinger** [comment]
Please don't ping that person. They aren't working on GrapheneOS anymore.

**Comment by thestinger** [comment]
Please don't ping her about it. They aren't working on GrapheneOS anymore.

**Comment by User1966** [comment]
Ah, sorry I didn't know girlbossceo wasn't working on GrapheneOS anymore.
I'll add this without @ to avoid any notifications.
